#! /bin/bash
#Launch an instance with 9000 and t2.medium
# go to sonarsource(download & install sonarqube)
cd /opt/
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-26.9.0.129388.zip
unzip sonarqube-26.9.0.129388.zip
yum install java-17-amazon-corretto -y
useradd sonar
chown sonar:sonar sonarqube-26.9.0.129388 -R
chmod 777 sonarqube-26.9.0.129388 -R
su - sonar

#run this on server manually to start the server
/opt/sonarqube-26.9.0.129388/bin/linux-x86-64
./sonar.sh start
--------------commented below code---added by haritha
#sh /opt/sonarqube-8.9.6.50800/bin/linux/sonar.sh start
#echo "user=admin & password=admin"
